[build]
  command = "yarn build"
  publish = "dist"
  base = "/"

[dev]
  command = "yarn dev"
  port = 5173
  publish = "dist"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.10.0"
  YARN_VERSION = "1.22.19"
  CI = "true"

# Enable CORS headers for API requests
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
